#!/bin/bash

SPACE_LABEL="$1"

yabai -m space --create
NEW_INDEX=$(yabai -m query --spaces --display | jq -r '
    map(select(."is-native-fullscreen" == false))[-1].index
')
yabai -m space $NEW_INDEX --label $SPACE_LABEL
