source ~/.config/tmux/keys.conf

# always start window at 1st position
set -g base-index 1
setw -g pane-base-index 1

# faster wait time
set -s escape-time 0

# reduce wait for next key-stoke time
set -g repeat-time 1

set -g allow-passthrough on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'sandudorogan/tmux-pane-tree'
set -g @tmux_pane_tree_install_agent_hooks 1   # optional
set -g @tmux_pane_tree_width   20
set -g @plugin 'accessd/tmux-agent-indicator'

source ~/.config/tmux/ui.conf

# options
set -s default-terminal 'xterm-256color'
set-option -g mouse on

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"

# Ensure terminal type is capable of 256 colors
set -g default-terminal "tmux-256color"

# tpm
run '~/.tmux/plugins/tpm/tpm'
